workflows:
  version: 2
  build-deploy:
    jobs:
      - build-java



version: 2
jobs:
  build-java:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - run:
          name: HTTPS checkout
          command: |
            # Workaround old docker images with incorrect $HOME
            # check https://github.com/docker/docker/issues/2968 for details
            if [ "${HOME}" = "/" ]
            then
              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
            fi

            echo "Replacing ssh repository URL $CIRCLE_REPOSITORY_URL with HTTPS version"
            CIRCLE_REPOSITORY_URL="https://${CIRCLE_USERNAME}:${GH_ACCESS_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"

            #eval working directory for tilde
            CIRCLE_WORKING_DIRECTORY=`eval echo $CIRCLE_WORKING_DIRECTORY`
            if [ -e ${CIRCLE_WORKING_DIRECTORY}/.git ]
            then
              cd ${CIRCLE_WORKING_DIRECTORY}
              git remote set-url origin "$CIRCLE_REPOSITORY_URL" || true
            else
              mkdir -p ${CIRCLE_WORKING_DIRECTORY}
              cd ${CIRCLE_WORKING_DIRECTORY}
              git clone "$CIRCLE_REPOSITORY_URL" .
            fi

            if [ -n "$CIRCLE_TAG" ]
            then
              git fetch --force origin "refs/tags/${CIRCLE_TAG}"
            else
              git fetch --force origin "master:remotes/origin/master"
            fi


            if [ -n "$CIRCLE_TAG" ]
            then
              git reset --hard "$CIRCLE_SHA1"
              git checkout -q "$CIRCLE_TAG"
            elif [ -n "$CIRCLE_BRANCH" ]
            then
              git reset --hard "$CIRCLE_SHA1"
              git checkout -q -B "$CIRCLE_BRANCH"
            fi

            git reset --hard "$CIRCLE_SHA1"
      - run:
          name: Install bazel
          command: |
            curl -L https://github.com/bazelbuild/bazel/releases/download/0.16.1/bazel-0.16.1-installer-linux-x86_64.sh -o bazel.sh
            chmod a+x bazel.sh
            sudo ./bazel.sh
      - run:
          name: build-java
          command: |
            cd java-tutorial
            bazel build //:ProjectRunner
      - store_artifacts:
          path: java-tutorial/bazel-bin/ProjectRunner

