workflows:
  version: 2
  build-deploy:
    jobs:
      - build-java



version: 2
jobs:
  build-java:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - run: bash .circleci/checkout.sh
      - run:
          name: Install bazel
          command: |
            curl -L https://github.com/bazelbuild/bazel/releases/download/0.16.1/bazel-0.16.1-installer-linux-x86_64.sh -o bazel.sh
            chmod a+x bazel.sh
            sudo ./bazel.sh
      - run:
          name: build-java
          command: |
            cd java-tutorial
            bazel build //:ProjectRunner
      - store_artifacts:
          path: java-tutorial/bazel-bin/ProjectRunner

